#!/bin/bash
source environment
IFS=$'\n' read -rd '' -a col1 <<< "$(grep -i -A1 "#I3BACKGROUNDGENERATORpage1.*" < "$HOME"/.config/i3/config | filter | awk '{print $1}')"
IFS=$'\n' read -rd '' -a col2 <<< "$(grep -i -o "#I3BACKGROUNDGENERATORpage1.*" < "$HOME"/.config/i3/config | sed 's&#I3BACKGROUNDGENERATORpage1:&&gI')"
for ((i=0; i<${#col1[@]}; i++ )); do
	echo "#####${col1[i]}###############${col2[i]}#####"
done | sedclean | sedcolor | column -t --separator=#